name: Deploy EC2 - Dev

on:
  push:
    paths:
      - 'infrastructure/ec2/**'
      - '.github/workflows/CD Pipelines/ec2/deploy-ec2-dev.yml'
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply - Dev'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: infrastructure/ec2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: DEBUG: Print contents of all .tf files
        run: |
          echo "📂 Dumping contents of all Terraform files:"
          find . -name "*.tf" -exec echo "--- {} ---" \; -exec cat {} \; -exec echo "" \;

      - name: 🔥 Full Terraform cleanup
        run: |
          echo "Removing all Terraform state & cached modules..."
          rm -rf .terraform
          rm -f .terraform.lock.hcl
          rm -f terraform.tfstate
          rm -f terraform.tfstate.backup
          echo "✅ Cleanup complete"

      - name: Terraform Init (force fresh modules)
        run: terraform init -upgrade -no-color

      - name: Terraform Plan
        run: terraform plan -var-file="dev.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="dev.tfvars"
