name: Deploy Dev Infrastructure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=infrastructure/eks init

      - name: Terraform Plan
        run: terraform -chdir=infrastructure/eks plan -var-file=../dev.tfvars

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infrastructure/eks apply -var-file=../dev.tfvars -auto-approve
